<script setup>
import {onBeforeUnmount,ref,watch} from 'vue'
import MemberCard from './OptimizerMemberCard.vue'
import SceneEditor from './OptimizerSceneEditor.vue'
import CommunityPanel from './OptimizerCommunityPanel.vue'
import NativeSource from './OptimizerNativeSource.vue'
import {outlineScript} from '@/api/artifact/artifactOptimizer.js'
import {characterLabel,profileLabel,weaponLabel,statLabel,elementLabels,buildLabel} from '@/features/artifact-optimizer/localization.js'
const props=defineProps({uid:{type:String,default:''},build:{type:Object,required:true},characters:{type:Array,default:()=>[]},catalog:{type:Object,default:()=>({})},templates:{type:Array,default:()=>[]},selected:{type:Array,default:()=>[]}})
const cName=key=>profileLabel(props.catalog,props.characters.find(c=>c.key===key)||{key})
const emit=defineEmits(['remove','save-buff-template','members-change','select-member','use-team','sampling'])
const loopChoices=ref([]),outlineError=ref('');let outlineTimer=null,outlineController=null,outlineGeneration=0
watch(()=>[props.build.id,props.build.rotation,props.build.nativeRotation?.enabled],([id,source],previous=[])=>{const generation=++outlineGeneration;clearTimeout(outlineTimer);outlineController?.abort();loopChoices.value=[];outlineError.value='';if(previous[0]===id&&previous[1]!==source&&props.build.roundPolicy)props.build.roundPolicy.loopIndex=0;if(props.build.nativeRotation?.enabled||!source?.trim())return;outlineTimer=setTimeout(async()=>{outlineController=new AbortController();try{const value=await outlineScript(source,outlineController.signal);if(generation===outlineGeneration)loopChoices.value=value}catch(e){if(generation===outlineGeneration&&!outlineController.signal.aborted)outlineError.value=e.message||'脚本结构暂不能识别，请检查语法'}},350)},{immediate:true})
onBeforeUnmount(()=>{outlineGeneration++;clearTimeout(outlineTimer);outlineController?.abort()})
function addConstraint(){props.build.constraints.push({id:crypto.randomUUID(),kind:'min_actions',character:props.build.members[0]?.character||'',action:'burst',threshold:1})}
function addBuff(){props.build.buffs.push({id:crypto.randomUUID(),kind:'stat',target:props.build.members[0]?.character||'',stat:'atk%',value:0.2,unit:'fraction',durationFrames:-1,anchor:'start',relationship:'pending_review',source:'手动补充'})}
function useTemplate(id){const template=props.templates.find(b=>b.id===id);if(template)props.build.buffs.push({...JSON.parse(JSON.stringify(template)),id:crypto.randomUUID(),enabled:true})}
function buffKindChanged(b){delete b.stat;delete b.element;delete b.attackTag;if(['resistance','defense_reduction'].includes(b.kind)){b.target='all_enemies';b.unit='fraction';if(b.kind==='resistance')b.element='pyro'}else{b.target=props.build.members[0]?.character||'';if(b.kind==='stat')b.stat='atk%';else b.attackTag='normal';b.unit='fraction'}}
function anchorChanged(b){delete b.sourceCharacter;delete b.action;if(b.anchor==='action'){b.sourceCharacter=props.build.members[0]?.character||'';b.action='skill'}}
</script>

<template>
  <section class="build-editor">
    <header class="workspace-heading"><div><p class="section-kicker">配队工作区</p><h2>{{ buildLabel(build) }}</h2><p class="hint">先选队员，再确认循环。个人装备始终来自你的背包。</p></div><el-button type="danger" plain @click="emit('remove')">删除方案</el-button></header>
    <details class="identity-settings"><summary>编辑方案名称与场景权重</summary><el-form label-position="top" class="grid build-identity">
      <el-form-item label="名称" class="span2"><el-input v-model="build.name"/></el-form-item>
      <el-form-item label="唯一场景权重（均衡）"><el-input-number v-model="build.weight" :min="0" :max="1000" :step="0.5"/></el-form-item>
    </el-form></details>
    <section class="team-block"><div class="block-heading"><h3>队伍与参算角色</h3><span class="section-meta">{{ build.members.length }} / 4 个位置</span></div><p class="hint">本次勾选计算的队员统一换成候选实物；其他队员须明确为固定实物或纯假设输入。固定队友的装备不会借出。</p>
    <div class="member-controls" id="optimizer-members"><el-select :model-value="build.members.map(m=>m.character)" multiple filterable :reserve-keyword="false" :multiple-limit="4" placeholder="选择最多四名队员" aria-label="配队队员多选" @update:model-value="keys=>emit('members-change',keys)"><el-option v-for="c in characters" :key="c.key" :value="c.key" :label="profileLabel(catalog,c)"/></el-select><el-button :disabled="!build.members.length" @click="emit('use-team')">将本队加入配装</el-button></div>
    <p class="hint">本方案已有 {{ build.members.length }} 名队员。本次参算在各卡片中选择，取消参算的队友仍按指定装备计算。</p>
    <div class="team-grid"><MemberCard v-for="member in build.members" :key="member.character" :member="member" :profile="characters.find(c=>c.key===member.character)||{key:member.character}" :catalog="catalog" :selected="selected.includes(member.character)" @select="value=>emit('select-member',member.character,value)" @remove="emit('members-change',build.members.filter(m=>m.character!==member.character).map(m=>m.character))"/></div>
    </section><section class="rotation-block"><div class="block-heading"><h3>循环脚本</h3><span class="section-meta">自动识别真实轮次</span></div><p class="hint">动作沿用 gcsim 语法，角色名支持中文（例如安柏、雷电将军）；编译时自动转为引擎标识，不改变原文。个人条件在上方编辑，此处不要重复声明 char、add stats 或敌人；模拟脚本不直接变成游戏输入。</p>
    <CommunityPanel :uid="uid" :build="build" :catalog="catalog" @sampling="value=>emit('sampling',value)"/>
    <div id="optimizer-rotation"></div><NativeSource :build="build"/>
    <details v-if="build.nativeRotation?.enabled"><summary>保留的gcsim参考（当前未启用）</summary><el-input :model-value="build.rotation" type="textarea" :rows="6" readonly aria-label="保留的gcsim参考"/></details>
    <el-input v-else v-model="build.rotation" type="textarea" :autosize="{minRows:8,maxRows:24}" spellcheck="false" aria-label="gcsim 循环脚本" placeholder="active 安柏;&#10;while 1 {&#10;  安柏 skill;&#10;  安柏 attack:3;&#10;}" class="script-input"/>
    <el-collapse v-if="build.scriptPrelude" class="details"><el-collapse-item title="辅助脚本逻辑（导入时保留，不是角色配置）" name="prelude"><div id="optimizer-scriptPrelude"></div><el-switch v-model="build.scriptPreludeEnabled" active-text="保留辅助逻辑"/><p class="hint">这里可能包含自动拾晶等会影响计算的函数。禁用会改变模拟机制，结果将标记为试算。</p><el-input v-model="build.scriptPrelude" type="textarea" :rows="8" aria-label="gcsim 辅助逻辑"/></el-collapse-item></el-collapse>
    </section>
    <details class="settings-disclosure"><summary><div><strong>场景与掉球</strong><span>{{ build.stopMode==='target_or_script'?'脚本/血量结束':`固定 ${build.duration} 秒` }} · {{ build.targets?.length||1 }} 个敌人{{ build.energy?.enabled?' · 已配置外部掉球':'' }}</span></div><span class="when-closed">展开设置</span><span class="when-open">收起设置</span></summary><SceneEditor :max-trajectory-seconds="catalog.capabilities?.maxTrajectorySeconds||0" :build="build" :loop-choices="loopChoices" :outline-error="outlineError"/></details>
    <el-collapse class="details"><el-collapse-item title="每轮硬约束" name="rounds">
      <el-button @click="addConstraint">添加每轮硬约束</el-button>
      <div v-for="(constraint,i) in build.constraints" :key="constraint.id" class="constraint-row"><el-select v-model="constraint.character" aria-label="约束角色"><el-option v-for="m in build.members" :key="m.character" :value="m.character" :label="cName(m.character)"/></el-select><el-select v-model="constraint.kind" aria-label="约束类型" @change="kind=>kind!=='min_actions'&&(delete constraint.action)"><el-option value="min_actions" label="最少成功动作次数"/><el-option value="max_failed_wait_frames" label="最多失败等待帧数"/><el-option value="min_effective_healing" label="最少有效治疗"/></el-select><el-select v-if="constraint.kind==='min_actions'" v-model="constraint.action" aria-label="约束动作"><el-option value="burst" label="元素爆发 Q"/><el-option value="skill" label="元素战技 E"/><el-option value="attack" label="普通攻击"/></el-select><el-input-number v-model="constraint.threshold" :min="0" aria-label="约束阈值"/><el-button text @click="build.constraints.splice(i,1)">删除</el-button></div>
    </el-collapse-item>
    <el-collapse-item title="通用增益补充与标记试算" name="buffs">
      <el-alert title="手动增益是明确假设，不是实机已触发的证据。无法安全替代原生效果时只允许额外或待复核，未知机制不会自动变成可用。" type="warning" :closable="false"/>
      <el-button class="add-buff" @click="addBuff">添加通用增益</el-button>
      <el-select model-value="" placeholder="复用已保存的增益模板" @change="useTemplate"><el-option v-for="b in templates" :key="b.id" :value="b.id" :label="`${b.source||b.kind} ${b.stat?statLabel(b.stat):b.element?elementLabels[b.element]:({normal:'普通攻击',skill:'元素战技',burst:'元素爆发'}[b.attackTag]||'')} ${b.value}`"/></el-select>
      <el-form v-for="(buff,i) in build.buffs" :key="buff.id" label-position="top" class="buff-form">
        <el-form-item label="此方案中启用"><el-switch :model-value="buff.enabled!==false" @update:model-value="value=>buff.enabled=value"/></el-form-item><el-form-item label="保存为可复用模板"><el-button @click="emit('save-buff-template',{...JSON.parse(JSON.stringify(buff)),id:crypto.randomUUID()})">保存模板</el-button></el-form-item>
        <el-form-item label="类型"><el-select v-model="buff.kind" @change="buffKindChanged(buff)"><el-option label="属性增益" value="stat"/><el-option label="敌人减抗" value="resistance"/><el-option label="敌人减防" value="defense_reduction"/><el-option label="限定攻击增伤" value="attack_bonus"/></el-select></el-form-item>
        <el-form-item label="作用对象"><el-select v-model="buff.target"><el-option v-if="['resistance','defense_reduction'].includes(buff.kind)" label="全部敌人" value="all_enemies"/><template v-else><el-option v-for="m in build.members" :key="m.character" :label="cName(m.character)" :value="m.character"/></template></el-select></el-form-item>
        <el-form-item v-if="buff.kind==='stat'" label="属性"><el-select v-model="buff.stat"><el-option v-for="s in ['hp','hp%','atk','atk%','def','def%','em','er','cr','cd','heal','pyro%','hydro%','cryo%','electro%','anemo%','geo%','dendro%','phys%']" :key="s" :value="s" :label="statLabel(s)"/></el-select></el-form-item>
        <el-form-item v-if="buff.kind==='resistance'" label="元素"><el-select v-model="buff.element"><el-option v-for="s in ['pyro','hydro','cryo','electro','anemo','geo','dendro','physical']" :key="s" :value="s" :label="elementLabels[s]"/></el-select></el-form-item>
        <el-form-item v-if="buff.kind==='attack_bonus'" label="攻击范围"><el-select v-model="buff.attackTag"><el-option value="normal" label="普攻"/><el-option value="skill" label="战技"/><el-option value="burst" label="爆发"/></el-select></el-form-item>
        <el-form-item label="数值（减抗用负数）"><el-input-number v-model="buff.value" :step="0.1"/></el-form-item><el-form-item label="单位"><el-select v-model="buff.unit"><el-option value="fraction" label="比例，0.2 = 20%"/><el-option value="flat" label="平值"/></el-select></el-form-item>
        <el-form-item label="触发时间锚"><el-select v-model="buff.anchor" @change="anchorChanged(buff)"><el-option value="start" label="开局"/><el-option value="round" label="声明的每轮边界"/><el-option value="action" label="动作成功时"/></el-select></el-form-item>
        <el-form-item v-if="buff.anchor==='action'" label="触发角色"><el-select v-model="buff.sourceCharacter"><el-option v-for="m in build.members" :key="m.character" :value="m.character" :label="cName(m.character)"/></el-select></el-form-item><el-form-item v-if="buff.anchor==='action'" label="触发动作"><el-select v-model="buff.action"><el-option value="skill" label="战技"/><el-option value="burst" label="爆发"/><el-option value="attack" label="普攻"/></el-select></el-form-item>
        <el-form-item label="持续帧数（60 帧 = 1 秒，-1 常驻）"><el-input-number v-model="buff.durationFrames" :min="-1" :max="36000"/></el-form-item><el-form-item label="与原生效果关系"><el-select v-model="buff.relationship" @change="()=>buff.reviewedEngineRevision=catalog.engineRevision"><el-option value="pending_review" label="可能重叠，待复核"/><el-option value="additional" label="确认是额外效果"/></el-select></el-form-item><el-form-item label="来源说明"><el-input v-model="buff.source"/></el-form-item><el-button text type="danger" @click="build.buffs.splice(i,1)">删除此增益</el-button>
      </el-form>
    </el-collapse-item></el-collapse>
    <el-checkbox v-model="build.allowPartial">明确允许上游标记不完整角色参与试算（结果会保留标记）</el-checkbox>
  </section>
</template>

<style scoped>
.settings-disclosure[open] .when-closed,.settings-disclosure:not([open]) .when-open{display:none}
.workspace-heading{padding:22px 24px;background:var(--el-bg-color);border:1px solid var(--el-border-color-lighter);border-radius:14px 14px 0 0;gap:20px}.workspace-heading h2{font-size:23px;margin:3px 0 0;letter-spacing:-.3px}.section-kicker{margin:0;font-size:12px;font-weight:600;color:var(--el-color-primary)}.workspace-heading .hint{margin:7px 0 0}.build-identity{padding:8px 24px 10px;border:1px solid var(--el-border-color-lighter);border-top:0;border-radius:0 0 14px 14px;background:var(--el-bg-color);margin-bottom:22px;grid-template-columns:minmax(0,1fr) 220px}.build-identity .span2{grid-column:auto}.team-block,.rotation-block{border:1px solid var(--el-border-color-lighter);border-radius:14px;padding:22px 24px;margin-bottom:22px;background:var(--el-bg-color)}.block-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:8px}.block-heading h3{margin:0;font-size:18px;letter-spacing:-.2px}.section-meta{color:var(--el-text-color-secondary);font-size:12px}.rotation-block{border-top:3px solid var(--el-color-primary)}.rotation-block :deep(.script-input textarea){min-height:240px;padding:18px 20px;background:var(--el-fill-color-light);border:1px solid var(--el-border-color-light);border-radius:10px;font-size:13px;color:var(--el-text-color-primary);box-shadow:none}.settings-disclosure{border:1px solid var(--el-border-color-lighter);border-radius:12px;padding:0 24px;background:var(--el-bg-color);margin-bottom:18px}.settings-disclosure>summary{list-style:none;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:19px 0;cursor:pointer}.settings-disclosure>summary strong{font-size:16px;display:block;margin-bottom:5px}.settings-disclosure>summary span{font-size:12px;color:var(--el-text-color-secondary)}.settings-disclosure[open]>summary{border-bottom:1px solid var(--el-border-color-light)}.settings-disclosure :deep(.scene-editor){padding-bottom:18px}.details{background:var(--el-bg-color);padding:0 20px;border-radius:12px;border:1px solid var(--el-border-color-lighter)}@media(max-width:650px){.workspace-heading,.team-block,.rotation-block{padding:18px 16px}.build-identity{grid-template-columns:1fr;padding:8px 16px}.settings-disclosure{padding:0 16px}.block-heading{align-items:start;flex-direction:column;gap:5px}}

.member-controls{display:flex;gap:12px;align-items:center}.member-controls>.el-select{flex:1;min-width:0}.team-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:18px 0 28px;align-items:start}@media(max-width:1050px){.team-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.team-grid{grid-template-columns:1fr}.member-controls{align-items:stretch;flex-direction:column}}

header{display:flex;justify-content:space-between;align-items:center}h2{font-size:21px;margin:0 0 16px}h3{font-size:16px;margin-top:24px}.hint{color:var(--el-text-color-secondary);font-size:13px;line-height:1.7}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0 14px}.span2{grid-column:span 2}.el-select{width:100%}.el-input-number{max-width:100%}.member{padding:12px 0;border-bottom:1px solid var(--el-border-color-lighter)}.member-row{display:grid;grid-template-columns:1fr 2fr auto;gap:12px;align-items:center;margin-bottom:10px}.override-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:12px}.details{margin:20px 0}.script-input :deep(textarea){font-family:Consolas,monospace;line-height:1.7}.round-controls,.round-row{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin-bottom:12px}.round-controls label,.round-row label{display:grid;gap:6px}.constraint-row{display:flex;gap:8px;margin-top:12px;align-items:center}.buff-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0 14px;border-bottom:1px solid var(--el-border-color-lighter);padding-top:14px}.add-buff{margin-top:12px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.buff-form,.override-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.constraint-row{flex-wrap:wrap}}@media(max-width:640px){.grid,.member-row,.buff-form,.override-grid{grid-template-columns:1fr}.span2{grid-column:auto}}

.build-editor .build-identity{grid-template-columns:minmax(0,1fr) 220px;border:0;margin:0;padding:4px 24px 12px}.identity-settings{margin:0 0 22px;background:var(--el-bg-color);border:1px solid var(--el-border-color-lighter);border-top:0;border-radius:0 0 14px 14px}.identity-settings>summary{cursor:pointer;padding:12px 24px;color:var(--el-text-color-secondary);font-size:12px}.workspace-heading{border-radius:14px 14px 0 0}.team-block .team-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:0}.team-block>.hint{font-size:12px}.team-block .member-controls{margin-top:12px}@media(max-width:820px){.team-block .team-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.team-block .team-grid{grid-template-columns:1fr}.build-editor .build-identity{grid-template-columns:1fr}}
</style>
