<script setup>
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import * as api from '@/api/artifact/artifactOptimizer.js'
import {metric,resultLabels} from '@/features/artifact-optimizer/model.js'
const props=defineProps({uid:{type:String,required:true},workspace:{type:Object,required:true},selected:{type:Array,default:()=>[]},snapshotId:{type:String,default:''},equipmentJob:{type:Object,default:null},beforeRun:{type:Function,required:true}})
const buildId=ref(props.workspace.builds[0]?.id||''),sourceName=ref(''),sourceText=ref(''),strategies=ref([]),actions=ref([]),error=ref(''),issues=ref([]),loading=ref(false),job=ref(null),preset=ref('moderate'),preview=ref(null),budget=ref(48),usePlan=ref(false)
let generation=0,timer=null
const build=computed(()=>props.workspace.builds.find(b=>b.id===buildId.value))
const members=computed(()=>build.value?.members||[])
const running=computed(()=>['QUEUED','RUNNING'].includes(job.value?.state))
const result=computed(()=>job.value?.result)
const history=ref([])
let restoring=false
watch(actions,value=>{if(!restoring&&build.value)build.value.rotationActions=JSON.parse(JSON.stringify(value))},{deep:true,flush:'sync'})
function loadActions(){restoring=true;actions.value=JSON.parse(JSON.stringify(build.value?.rotationActions||[]));restoring=false}
function stopPoll(){if(timer!==null)clearTimeout(timer);timer=null}
function reset(){generation++;stopPoll();loadActions();job.value=null;preview.value=null;issues.value=[];loading.value=false}
watch(()=>props.uid,reset);watch(buildId,reset)
async function discover(){loading.value=true;error.value='';try{strategies.value=await api.listCombatStrategies()}catch(e){error.value=e.message||String(e)}finally{loading.value=false}}
function add(){actions.value.push({character:members.value[0]?.character||'',kind:'skill'})}
function kindChanged(a){if(['attack_seconds','wait'].includes(a.kind))a.seconds=2;else delete a.seconds}
async function importSource(pasted=false){const version=generation,account=props.uid;if(!(await props.beforeRun()))return;loading.value=true;error.value='';try{const parsed=await api.importCombatStrategy(account,{buildId:buildId.value,...(pasted?{source:sourceText.value}:{name:sourceName.value})});if(version!==generation)return;issues.value=[...(parsed.issues||[]),...(parsed.note?[parsed.note]:[])];if(parsed.supported)actions.value=parsed.actions;else error.value='原策略含未支持的语义，尚未导入。请保留原文作参考，或明确编辑有限动作序列。'}catch(e){if(version===generation)error.value=e.message||String(e)}finally{if(version===generation)loading.value=false}}
async function poll(id,version,account){try{const value=await api.loadOptimization(account,id);if(version!==generation)return;job.value=value;if(['QUEUED','RUNNING'].includes(value.state))timer=setTimeout(()=>poll(id,version,account),1500)}catch(e){if(version===generation)error.value=e.message||String(e)}}
async function start(){const version=generation,account=props.uid;if(!(await props.beforeRun()))return;loading.value=true;error.value='';preview.value=null;try{const value=await api.startRotation(account,{workspaceVersion:props.workspace.version,buildId:buildId.value,snapshotId:props.snapshotId,characters:props.selected,actions:JSON.parse(JSON.stringify(actions.value)),rotationBudget:budget.value,wallTimeSeconds:120,equipmentJobId:usePlan.value?props.equipmentJob?.id:''});if(version!==generation)return;job.value=value;await poll(value.id,version,account)}catch(e){if(version===generation)error.value=e.message||String(e)}finally{if(version===generation)loading.value=false}}
async function cancel(){const id=job.value?.id,version=generation;try{const value=await api.cancelOptimization(props.uid,id);if(version===generation){job.value=value;stopPoll()}}catch(e){error.value=e.message||String(e)}}
async function createPreview(){error.value='';try{preview.value=await api.previewRotation(props.uid,job.value.id,preset.value)}catch(e){error.value=e.message||String(e)}}
function download(){const blob=new Blob([preview.value.script],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gcsim-${job.value.id}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function applyToBuild(){const target=props.workspace.builds.find(b=>b.id===job.value?.buildId);if(target&&result.value?.script){target.rotation=result.value.script;target.rotationActions=JSON.parse(JSON.stringify(result.value.actions));loadActions()}}
async function loadHistory(){const version=generation,account=props.uid;try{const values=await api.listOptimizations(account);if(version===generation)history.value=values.filter(j=>j.kind==='rotation')}catch(e){if(version===generation)error.value=e.message||String(e)}}
async function showHistory(id){const version=generation,account=props.uid;try{const value=await api.loadOptimization(account,id);if(version!==generation)return;job.value=value;preview.value=null;stopPoll();if(['QUEUED','RUNNING'].includes(value.state))await poll(id,version,account)}catch(e){if(version===generation)error.value=e.message||String(e)}}
onMounted(()=>{loadActions();loadHistory()})
onBeforeUnmount(()=>{generation++;stopPoll()})
</script>

<template>
  <section class="rotation-panel">
    <header><h2>战斗循环自动优化</h2><p>复用同一队伍的个人条件、敌人、Buff 和装备；自动搜索动作顺序与普攻 / 等待时长，再用独立样本验证。</p></header>
    <el-select v-if="history.length" placeholder="查看或恢复循环计算" :model-value="job?.id" @change="showHistory"><el-option v-for="h in history" :key="h.id" :value="h.id" :label="`${h.createdAt} ${h.state}`"/></el-select>
    <el-alert v-if="error" :title="error" type="error" :closable="false"/>
    <el-form label-position="top" class="setup-grid"><el-form-item label="配队 Build"><el-select v-model="buildId"><el-option v-for="b in workspace.builds" :key="b.id" :value="b.id" :label="b.name"/></el-select></el-form-item><el-form-item label="装备输入"><el-switch v-model="usePlan" :disabled="!equipmentJob?.result?.plan?.qualified" active-text="最近合格配装" inactive-text="扫描时实装"/></el-form-item><el-form-item label="候选预算"><el-input-number v-model="budget" :min="4" :max="512" :step="16"/></el-form-item></el-form>
    <p class="hint">背包：{{ snapshotId||'未选择' }}。参选角色：{{ selected.join('、')||'请先到角色页勾选角色' }}。循环优化以本场景实际整队 DPS 为目标，不改变圣遗物归属。</p>
    <el-collapse><el-collapse-item title="接入已有 BetterGI 战斗策略" name="import"><div class="source-toolbar"><el-button :loading="loading" @click="discover">读取策略目录</el-button><el-select v-model="sourceName" filterable placeholder="选择现有 .txt / .json 策略"><el-option v-for="name in strategies" :key="name" :value="name" :label="name"/></el-select><el-button :disabled="!sourceName||!buildId" @click="importSource(false)">导入有限动作</el-button></div><el-input v-model="sourceText" type="textarea" :rows="5" aria-label="原生战斗策略正文" placeholder="也可粘贴策略，例如：&#10;安柏 e,attack(2)&#10;凯亚 q(required)"/><el-button class="pasted-import" :disabled="!sourceText||!buildId" @click="importSource(true)">解析粘贴内容</el-button><p class="hint">未知分支、Buff 记录 / keep 依赖和不确定的动作转换会明确拒绝，不会被删掉后冒充可执行策略。社区 gcsim 脚本可在 Build 循环区作为模拟参考。</p><a href="https://gcsim.app/" target="_blank" rel="noopener noreferrer">打开 gcsim 社区参考</a></el-collapse-item></el-collapse>
    <el-alert v-for="issue in issues" :key="issue" :title="issue" type="warning" :closable="false" class="issue"/>
    <h3>可优化的一轮动作</h3><p class="hint">当前支持战技、爆发、有明确秒数的普攻与等待。搜索保留 E / Q 数量；持续 Q、治疗和等待要求仍在 Build 的硬约束里定义。</p>
    <el-empty v-if="!actions.length" description="导入受支持的现有策略，或添加动作后开始搜索。" :image-size="70"/>
    <div v-for="(a,i) in actions" :key="i" class="action-row"><span class="order">{{ i+1 }}</span><el-select v-model="a.character" aria-label="动作角色"><el-option v-for="m in members" :key="m.character" :value="m.character" :label="workspace.characters.find(c=>c.key===m.character)?.name||m.character"/></el-select><el-select v-model="a.kind" aria-label="动作类型" @change="kindChanged(a)"><el-option value="skill" label="元素战技 E"/><el-option value="burst" label="元素爆发 Q"/><el-option value="attack_seconds" label="普攻时段"/><el-option value="wait" label="等待"/></el-select><el-input-number v-if="['attack_seconds','wait'].includes(a.kind)" v-model="a.seconds" :min="0.25" :max="30" :step="0.25" aria-label="动作秒数"/><el-button text :disabled="i===0" @click="[actions[i-1],actions[i]]=[actions[i],actions[i-1]]">上移</el-button><el-button text type="danger" @click="actions.splice(i,1)">移除</el-button></div>
    <div class="actions"><el-button :disabled="!buildId||actions.length>=80" @click="add">添加动作</el-button><el-button v-if="running" type="danger" plain @click="cancel">取消循环优化</el-button><el-button type="primary" :loading="loading" :disabled="!actions.length||!selected.length||!snapshotId||running" @click="start">自动搜索循环</el-button></div>
    <section v-if="job" class="rotation-result" aria-live="polite"><h3>{{ result?resultLabels[result.status]||result.status:({QUEUED:'等待计算',RUNNING:'正在搜索循环',CANCELLED:'循环优化已取消',FAILED:'循环优化失败'}[job.state]||job.state) }}</h3><el-alert v-if="job.error" :title="job.error" type="error" :closable="false"/><el-skeleton v-if="running" :rows="4" animated/><template v-if="result?.report"><div class="dps"><span>原序列 DPS <strong>{{ metric(result.baseline?.meanDps) }}</strong></span><span>候选 DPS <strong>{{ metric(result.report.meanDps) }}</strong></span><span>实际评估 <strong>{{ result.evaluations }}</strong></span></div><el-alert :title="result.report.validation.state==='passed'?'本次独立验证样本集通过，不等于实机已验证':'验证未通过'" type="info" :closable="false"/><el-alert v-if="result.status==='feasible_uncertain'" title="改善尚不确定，保留原序列供比较。" type="warning" :closable="false"/><el-input :model-value="result.script" type="textarea" :rows="8" readonly aria-label="优化后的 gcsim 循环"/><el-button @click="applyToBuild">应用到此 Build 的模拟循环</el-button><div class="preview-controls"><el-radio-group v-model="preset"><el-radio-button value="relaxed">宽松</el-radio-button><el-radio-button value="moderate">适中</el-radio-button><el-radio-button value="strict">严格</el-radio-button></el-radio-group><el-button @click="createPreview">预览执行策略</el-button></div><template v-if="preview"><el-alert :title="preview.note" type="warning" :closable="false"/><el-alert v-for="a in preview.assumptions||[]" :key="a" :title="a" type="warning" :closable="false"/><el-input :model-value="preview.script" type="textarea" :rows="10" readonly aria-label="BetterGI 执行策略预览"/><el-checkbox :model-value="false" disabled>不会自动启动战斗或覆盖原策略</el-checkbox><el-button type="primary" @click="download">确认并下载新策略</el-button></template></template><el-alert v-else-if="result" v-for="issue in result.issues||[]" :key="issue" :title="issue" type="warning" :closable="false"/></section>
  </section>
</template>

<style scoped>
h2{font-size:21px}h3{font-size:16px}header p,.hint{font-size:13px;color:var(--el-text-color-secondary);line-height:1.7}.setup-grid{display:grid;grid-template-columns:2fr 2fr 1fr;gap:18px}.el-select{width:100%}.source-toolbar,.actions,.preview-controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:16px 0}.source-toolbar .el-select{flex:1;min-width:220px}.pasted-import{margin-top:12px}.issue{margin-top:8px}.action-row{display:flex;gap:10px;align-items:center;margin:12px 0}.action-row .el-select{max-width:230px}.order{font-variant-numeric:tabular-nums;width:26px}.rotation-result{border-top:1px solid var(--el-border-color);margin-top:24px;padding-top:16px}.dps{display:flex;gap:32px;margin:20px 0}.dps span{display:grid;gap:8px;font-size:12px;color:var(--el-text-color-secondary)}.dps strong{font-size:25px;color:var(--el-text-color-primary);font-variant-numeric:tabular-nums}.rotation-result :deep(textarea){font-family:Consolas,monospace;line-height:1.7;margin:14px 0}@media(max-width:760px){.setup-grid{grid-template-columns:1fr}.action-row{flex-wrap:wrap}.action-row .el-select{max-width:100%;flex:1 1 130px}.dps{gap:20px}}
</style>
