import service from '@utils/request.js'
const root='/jwt/artifacts/optimizer'
async function data(promise){return (await promise).data}
export const loadWorkspace=uid=>data(service.get(`${root}/workspace`,{params:{uid}}))
export const saveWorkspace=(uid,value)=>data(service.put(`${root}/workspace`,value,{params:{uid}}))
export const loadCatalog=()=>data(service.get(`${root}/catalog`))
export const enkaPreview=uid=>data(service.post(`${root}/enka-preview`,null,{params:{uid}}))
export const loadSnapshots=uid=>data(service.get(`${root}/snapshots`,{params:{uid}}))
export const loadSnapshot=(uid,id)=>data(service.get(`${root}/snapshots/${encodeURIComponent(id)}`,{params:{uid}}))
export const startOptimization=(uid,selection)=>data(service.post(`${root}/jobs`,selection,{params:{uid}}))
export const loadOptimization=(uid,id)=>data(service.get(`${root}/jobs/${encodeURIComponent(id)}`,{params:{uid}}))
export const listOptimizations=uid=>data(service.get(`${root}/jobs`,{params:{uid}}))
export const cancelOptimization=(uid,id)=>data(service.post(`${root}/jobs/${encodeURIComponent(id)}/cancel`,null,{params:{uid}}))
export const listCombatStrategies=()=>data(service.get(`${root}/rotations/strategies`))
export const importCombatStrategy=(uid,input)=>data(service.post(`${root}/rotations/import`,input,{params:{uid}}))
export const startRotation=(uid,input)=>data(service.post(`${root}/rotations/jobs`,input,{params:{uid}}))
export const previewRotation=(uid,id,preset)=>data(service.post(`${root}/rotations/jobs/${encodeURIComponent(id)}/preview`,null,{params:{uid,preset}}))
export const previewEquipment=(uid,jobId)=>data(service.post(`${root}/equipment/preview`,{jobId},{params:{uid}}))
export const confirmEquipment=(uid,id,digest)=>data(service.post(`${root}/equipment/${encodeURIComponent(id)}/confirm`,{digest,acceptImpacts:true},{params:{uid}}))
export const getEquipment=(uid,id)=>data(service.get(`${root}/equipment/${encodeURIComponent(id)}`,{params:{uid}}))
export const cancelEquipment=(uid,id)=>data(service.post(`${root}/equipment/${encodeURIComponent(id)}/cancel`,null,{params:{uid}}))
export const recoverEquipment=(uid,id,snapshotId)=>data(service.post(`${root}/equipment/${encodeURIComponent(id)}/recovery-preview`,{snapshotId},{params:{uid}}))
export const checkEngineUpdates=()=>data(service.post(`${root}/engine/check`))
export const installEnginePackage=assetId=>data(service.post(`${root}/engine/install`,{assetId,confirmed:true}))
export const rollbackEngine=()=>data(service.post(`${root}/engine/rollback`,{confirmed:true}))
